--- 

- hosts: all
  become: yes
  vars_files:
  - vars.yml
  - vault.yml
  tasks: 
  - name: Add user
    user:
     name: "{{ item.username }}"
     password: "{{ item.password | password_hash('sha512') }}"
    with_items: "{{ users }}"
    when: users | length > 0 
