- name: Update all packages, deploy SSH Keys to AWX Node and install AWX with all relevant packages
  hosts: awx
  become: yes
  become_user: root
  become_method: sudo

  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py
  tasks:
    - name: Update all packages
      apt:
        upgrade: dist

  roles:
    - deploy_ssh_keys
    - python
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
