---
- name: Update all packages, deploy SSH Keys to Managed Nodes, Install Python, Add a new User, Install Webserver, Install Docker and Create Container
  hosts: all
  become: yes
  tasks:
    - name: Upgrade all packages
      apt:
   
  roles:
    - deploy_ssh_keys
    - python
    - add_user
    - webserver
    - docker
