---

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install pip
  apt:
    name: python-pip
    state : present

- import_tasks: ansible.yml

- import_tasks: ../../docker/tasks/install_docker.yml
- include_vars: ../../docker/vars/main.yml

- import_tasks: ../../docker/handlers/main.yml
#- include_role: 
#    name: docker

- name: Install docker-compose and docker python module
  pip:
    name:
      - docker-compose
     # - docker
    executable: pip

- name: Install git, npm and build-essential (including gcc, g++ and make)
  apt:
    name:
      - git
      - nodejs
      - npm
      - build-essential
    state: present
    update_cache: yes

- name: Install npm
  npm:
    name: npm
    global: yes
