---

#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist

#- name: Install pip
#  apt:
#    name: python-pip
#    state: latest

- name: Upgrade pip
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

- import_tasks: ansible.yml

- include_vars: ../../docker/defaults/main.yml
- include_tasks: ../../docker/handlers/main.yml
- import_tasks: ../../docker/tasks/install_docker.yml

#- name: Install docker-compose and docker python module (which is delivered with docker-compose or in installation with docker)
#  pip:
#    name:
#      - docker-compose
#      - docker-py
#    executable: pip3
#    state: latest

- name: Delete existing docker-compose
  file:
    path: /usr/local/bin/docker-compose
    state: absent

- name: Ensure curl is present
  package:
    name: curl
    state: present

#- name: Install docker-compose
#  get_url:
#    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
#    dest: /usr/local/bin/docker-compose
#    mode: 0755

- name: Install git, npm and build-essential (including gcc, g++ and make)
  apt:
    name:
      - git
      - nodejs
      - npm
      - build-essential
      - python3-setuptools
    state: present
    update_cache: yes

- name: Install docker-compose with pip
  pip:
    name: docker-compose
    executable: pip
    state: present

- name: Clone awx source code from GitHub
  git:
    repo: 'https://github.com/ansible/awx.git'
    dest: /home/itsadmin/awx

