---

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install pip
  apt:
    name: python3-pip
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

- import_tasks: ansible.yml

- import_tasks: ../../docker/handlers/main.yml
- include_vars: ../../docker/vars/main.yml
- import_tasks: ../../docker/tasks/install_docker.yml



#- include_role:
#    name: docker

#- name: Install docker-compose and docker python module (which is delivered with docker-compose or in installation with docker)
#  pip:
#    name:
#      - docker-compose
#      # - docker
#    executable: pip3
#    state: latest

- name: Delete existing docker-compose version
  file:
    path: "/usr/local/bin/docker-compose"
    state: absent

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
    dest: "/usr/local/bin/docker-compose"
    mode: 0755

- name: Install git, npm and build-essential (including gcc, g++ and make)
  apt:
    name:
      - git
      - nodejs
      - npm
      - build-essential
    state: present
    update_cache: yes

- name: Install npm
  npm:
    name: npm
    global: yes
    state: latest
