---

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# Install Ansible
- import_tasks: ansible.yml

- name: Install pip
  package:
    name:
    state : python3-pip

- import_tasks: ../../docker/tasks/install_docker.yml

- name: Install docker-compose and docker python module
  pip:
    name:
      - docker-compose
      - docker

- name: Install git, npm and build-essential (including gcc, g++ and make)
  apt:
    name:
      - git
      - nodejs
      - npm
      - build-essential
    state: present
    update_cache: yes

- name: Install npm
  npm:
    name: npm
    global: yes
