---
#- hosts: all
#  become: yes
#  remote_user: root
#  tasks:
  
  - name: Install python3 and python3-pip
    apt:
      name:
       - python3
       - python3-pip
      state: latest
      update_cache: yes

