---

#- name: Add user 
#  hosts: all
#  tasks:
    - include_vars: ../vars/main.yml
    - name: Add a new user with username and commentname, who are defined in vars
      user:
        name: "{{ item.username }}"
        comment: "{{ item.name }}"
      with_items: "{{ users }}"
      when: users | length > 0