---

- name: Add user 
  hosts: all
  tasks:
    - name: Add a new user with username, commentname and group
      user:
        name: "{{ username }}"
        comment: "{{ name }}"
        group: "{{ groupname }}"
