---
#- hosts: webservers
#  become: yes
#  tasks:

# Install MySQL, Apache, PHP
  - include_vars: ../vars/main.yml

  - name: Check package if installed and install if not
    apt:
      name: "{{ item }}"
      update_cache: yes
      cache_valid_time: 3600
      state: present
    with_items: "{{ lamp_packages }}"

  - name: Check if package server is running
    service:
      name: "{{ item }}"
      state: started
    with_items: "{{ lamp_packages }}"

  - name: Start service on boot
    service:
      name: "{{ item }}"
      enabled: yes
    with_items: "{{ lamp_packages }}"
