---
#- hosts: webservers
#  become: yes
#  tasks:

# Install MySQL, Apache, PHP
  - name: Check package if installed and installs if not present
    apt:
      name:
        - mysql-server
        - apache2
        - php
        - php-mysql
        - libapache2-mod-php
      update_cache: yes
      cache_valid_time: 3600
      state: present

  - name: Check if package server is running and enable to start on boot
    service:
      name:
        - mysql
        - apache2
      state: restarted
      enabled: yes

