---
- hosts: webservers
  become: yes
  tasks:
  - name: Ensure httpd is on latest version
    apt:
      name: apache2
      state: latest
 
  - name: Ensure httpd is running
    service:
      name: apache2
      state: started
      enabled: yes
